[project]
name = "supra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.5",
    "langchain-ollama>=0.2.0",
    "langchain-groq>=0.1.0",
    "python-dotenv>=1.0.0",
    "langchain>=0.2.0",
]
